- name: "Installation d'Apache"
  hosts: all
  tasks:
      - name: Inscrire le nouveau dépôt
        apt_repository:
           repo: deb http://ftp.fr.debian.org/debian/ stretch main
           state: present
           update_cache: yes
         
      - name: Installation d'apache2 
        apt:
          name: apache2,ca-certificates,apt-transport-https
          state: present 
        
      - name: Démarrer le service Apache
        service:
          name: apache2
          state: started
          enabled: yes

- name: Installation de Mysql 
  hosts: all
  tasks:
     
      - name : Installation de python-pip
        apt :  
          name : python-pip
          state : present    
            
      - name: Installer le module Python pour Mysql
        pip:
          name: PyMySQL
        
      - name: Installation de python-mysqldb, mysqlserveur
        apt:
          name: python-mysqldb,mysql-server
          state: present 
      
      - name: Création d'une base de données    
        mysql_db:    
         name: "{{mysql_db}}"
         state: present  
         login_unix_socket: /var/run/mysqld/mysqld.sock  
      
      - name: Création de l'utilisateur eleve et affectation des privilèges sur une base de données
        mysql_user:
         name: "{{mysql_user}}"
         password: "{{mysql_password}}"
         host: localhost
         priv: "{{mysql_db}}.*:ALL,GRANT"
         login_unix_socket: /var/run/mysqld/mysqld.sock
         
- name: PHPMYADMIN Installation
  hosts: all
  tasks:   
            
      - name : Installation de debconf-utils
        apt :  
          name : debconf-utils
          state : present
          
      - name: Installation de dbconfig
        debconf: 
           name: phpmyadmin 
           question: phpmyadmin/dbconfig-install 
           value: true 
           vtype: boolean
          
           name: phpmyadmin
           question: phpmyadmin/app-password-confirm
           value: btsinfo 
           vtype: password
        
           name: phpmyadmin
           question: phpmyadmin/mysql/admin-pass
           value: btsinfo 
           vtype: password
          
           name: phpmyadmin
           question: phpmyadmin/mysql/app-pass
           value: btsinfo 
           vtype: password
          
           name: phpmyadmin
           question: phpmyadmin/reconfigure-webserve
           value: apache2 
           vtype: multiselect
          
      - name: configure site
        file :
          path: /var/www/html/phpmyadmin
          src: /usr/share/phpmyadmin
          state: link
          
      - name : Installation de PhpMyAdmin
        apt :  
          name : phpmyadmin
          state : present
          
      - name: Démarrer le service Apache
        service:
          name: apache2
          state: restarted
          enabled: yes